services:
  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    depends_on:
      - db
    env_file:
      - .env.sample

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tg_traffic
    ports:
      - "5435:5432"
    env_file:
      - .env.sample
